# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/AD4030_Voltage_constraints.xdc

# Block Designs: bd/AD4030_Voltage/AD4030_Voltage.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AD4030_Voltage || ORIG_REF_NAME==AD4030_Voltage} -quiet] -quiet

# IP: bd/AD4030_Voltage/ip/AD4030_Voltage_processing_system7_0_0/AD4030_Voltage_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AD4030_Voltage_processing_system7_0_0 || ORIG_REF_NAME==AD4030_Voltage_processing_system7_0_0} -quiet] -quiet

# IP: bd/AD4030_Voltage/ip/AD4030_Voltage_xbar_0/AD4030_Voltage_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AD4030_Voltage_xbar_0 || ORIG_REF_NAME==AD4030_Voltage_xbar_0} -quiet] -quiet

# IP: bd/AD4030_Voltage/ip/AD4030_Voltage_ps7_0_axi_periph_0/AD4030_Voltage_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AD4030_Voltage_ps7_0_axi_periph_0 || ORIG_REF_NAME==AD4030_Voltage_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/AD4030_Voltage/ip/AD4030_Voltage_rst_ps7_0_100M_0/AD4030_Voltage_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AD4030_Voltage_rst_ps7_0_100M_0 || ORIG_REF_NAME==AD4030_Voltage_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/AD4030_Voltage/ip/AD4030_Voltage_axi_gpio_0_0/AD4030_Voltage_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AD4030_Voltage_axi_gpio_0_0 || ORIG_REF_NAME==AD4030_Voltage_axi_gpio_0_0} -quiet] -quiet

# IP: bd/AD4030_Voltage/ip/AD4030_Voltage_axi_timer_0_0/AD4030_Voltage_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AD4030_Voltage_axi_timer_0_0 || ORIG_REF_NAME==AD4030_Voltage_axi_timer_0_0} -quiet] -quiet

# IP: bd/AD4030_Voltage/ip/AD4030_Voltage_axi_gpio_1_1/AD4030_Voltage_axi_gpio_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AD4030_Voltage_axi_gpio_1_1 || ORIG_REF_NAME==AD4030_Voltage_axi_gpio_1_1} -quiet] -quiet

# IP: bd/AD4030_Voltage/ip/AD4030_Voltage_auto_pc_0/AD4030_Voltage_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AD4030_Voltage_auto_pc_0 || ORIG_REF_NAME==AD4030_Voltage_auto_pc_0} -quiet] -quiet

# XDC: /home/grzegorz/git/ARTY_Z7/AD4030/Software/vivado/AD4030-Voltage/AD4030-Voltage.gen/sources_1/bd/AD4030_Voltage/AD4030_Voltage_ooc.xdc
