# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/grzegorz/git/ARTY_Z7/AD4030/Software/vivado/AD4030-Voltage/AD4030-Voltage.srcs/sources_1/bd/AD4030_Voltage/ip/AD4030_Voltage_axi_gpio_0_0/AD4030_Voltage_axi_gpio_0_0.xci
# IP: The module: 'AD4030_Voltage_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/grzegorz/git/ARTY_Z7/AD4030/Software/vivado/AD4030-Voltage/AD4030-Voltage.gen/sources_1/bd/AD4030_Voltage/ip/AD4030_Voltage_axi_gpio_0_0/AD4030_Voltage_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'AD4030_Voltage_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/grzegorz/git/ARTY_Z7/AD4030/Software/vivado/AD4030-Voltage/AD4030-Voltage.gen/sources_1/bd/AD4030_Voltage/ip/AD4030_Voltage_axi_gpio_0_0/AD4030_Voltage_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AD4030_Voltage_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/grzegorz/git/ARTY_Z7/AD4030/Software/vivado/AD4030-Voltage/AD4030-Voltage.gen/sources_1/bd/AD4030_Voltage/ip/AD4030_Voltage_axi_gpio_0_0/AD4030_Voltage_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'AD4030_Voltage_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/grzegorz/git/ARTY_Z7/AD4030/Software/vivado/AD4030-Voltage/AD4030-Voltage.srcs/sources_1/bd/AD4030_Voltage/ip/AD4030_Voltage_axi_gpio_0_0/AD4030_Voltage_axi_gpio_0_0.xci
# IP: The module: 'AD4030_Voltage_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/grzegorz/git/ARTY_Z7/AD4030/Software/vivado/AD4030-Voltage/AD4030-Voltage.gen/sources_1/bd/AD4030_Voltage/ip/AD4030_Voltage_axi_gpio_0_0/AD4030_Voltage_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'AD4030_Voltage_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/grzegorz/git/ARTY_Z7/AD4030/Software/vivado/AD4030-Voltage/AD4030-Voltage.gen/sources_1/bd/AD4030_Voltage/ip/AD4030_Voltage_axi_gpio_0_0/AD4030_Voltage_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AD4030_Voltage_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/grzegorz/git/ARTY_Z7/AD4030/Software/vivado/AD4030-Voltage/AD4030-Voltage.gen/sources_1/bd/AD4030_Voltage/ip/AD4030_Voltage_axi_gpio_0_0/AD4030_Voltage_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'AD4030_Voltage_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
