# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ThreadX/ThreadX.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ThreadX || ORIG_REF_NAME==ThreadX} -quiet] -quiet

# IP: bd/ThreadX/ip/ThreadX_processing_system7_0_0/ThreadX_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ThreadX_processing_system7_0_0 || ORIG_REF_NAME==ThreadX_processing_system7_0_0} -quiet] -quiet

# IP: bd/ThreadX/ip/ThreadX_axi_gpio_0_0/ThreadX_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ThreadX_axi_gpio_0_0 || ORIG_REF_NAME==ThreadX_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ThreadX/ip/ThreadX_ps7_0_axi_periph_0/ThreadX_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ThreadX_ps7_0_axi_periph_0 || ORIG_REF_NAME==ThreadX_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ThreadX/ip/ThreadX_rst_ps7_0_100M_0/ThreadX_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ThreadX_rst_ps7_0_100M_0 || ORIG_REF_NAME==ThreadX_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/ThreadX/ip/ThreadX_auto_pc_0/ThreadX_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ThreadX_auto_pc_0 || ORIG_REF_NAME==ThreadX_auto_pc_0} -quiet] -quiet

# XDC: /home/grzegorz/git/ARTY_Z7/ThreadX/ThreadX.gen/sources_1/bd/ThreadX/ThreadX_ooc.xdc
