library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.ad4030_pkg.all;
use ieee.std_logic_textio.all;
use std.textio.all;

entity ad4030_axi_tb is
end entity ad4030_axi_tb;

architecture testbench of ad4030_axi_tb is

    constant clock_period : time := 10 ns; -- 100 MHz

    signal clk   : std_logic;
    signal rst_n : std_logic;

    -- AD4030 
    signal cs_n            : std_logic;
    signal busy            : std_logic;
    signal miso0           : std_logic;
    signal miso1           : std_logic;
    signal miso2           : std_logic;
    signal miso3           : std_logic;
    signal sclk            : std_logic;
    signal mosi            : std_logic;
    signal conv            : std_logic;
    -- AXI4 Lite interface
    signal s00_axi_awaddr  : std_logic_vector(31 downto 0);
    signal s00_axi_awprot  : std_logic_vector(2 downto 0);
    signal s00_axi_awvalid : std_logic;
    signal s00_axi_awready : std_logic;
    signal s00_axi_wdata   : std_logic_vector(31 downto 0);
    signal s00_axi_wstrb   : std_logic_vector(3 downto 0);
    signal s00_axi_wvalid  : std_logic;
    signal s00_axi_wready  : std_logic;
    signal s00_axi_bresp   : std_logic_vector(1 downto 0);
    signal s00_axi_bvalid  : std_logic;
    signal s00_axi_bready  : std_logic;
    signal s00_axi_araddr  : std_logic_vector(31 downto 0);
    signal s00_axi_arprot  : std_logic_vector(2 downto 0);
    signal s00_axi_arvalid : std_logic;
    signal s00_axi_arready : std_logic;
    signal s00_axi_rdata   : std_logic_vector(31 downto 0);
    signal s00_axi_rresp   : std_logic_vector(1 downto 0);
    signal s00_axi_rvalid  : std_logic;
    signal s00_axi_rready  : std_logic;
                signal sine_hex : std_logic_vector(31 downto 0);


    component AD4030
        generic(
            C_S00_AXI_DATA_WIDTH   : integer := 32;
            C_S00_AXI_ADDR_WIDTH   : integer := 32;
            C_M00_AXIS_TDATA_WIDTH : integer := 32;
            C_M00_AXIS_START_COUNT : integer := 32
        );
        port(
            clk_in          : in  std_logic;
            rst_n_in        : in  std_logic;
            cs_n_out        : out std_logic;
            busy_in         : in  std_logic;
            miso0_in        : in  std_logic;
            miso1_in        : in  std_logic;
            miso2_in        : in  std_logic;
            miso3_in        : in  std_logic;
            sclk_out        : out std_logic;
            mosi_out        : out std_logic;
            conv_out        : out std_logic;
            s00_axi_aclk    : in  std_logic;
            s00_axi_aresetn : in  std_logic;
            s00_axi_awaddr  : in  std_logic_vector(C_S00_AXI_ADDR_WIDTH - 1 downto 0);
            s00_axi_awprot  : in  std_logic_vector(2 downto 0);
            s00_axi_awvalid : in  std_logic;
            s00_axi_awready : out std_logic;
            s00_axi_wdata   : in  std_logic_vector(C_S00_AXI_DATA_WIDTH - 1 downto 0);
            s00_axi_wstrb   : in  std_logic_vector((C_S00_AXI_DATA_WIDTH / 8) - 1 downto 0);
            s00_axi_wvalid  : in  std_logic;
            s00_axi_wready  : out std_logic;
            s00_axi_bresp   : out std_logic_vector(1 downto 0);
            s00_axi_bvalid  : out std_logic;
            s00_axi_bready  : in  std_logic;
            s00_axi_araddr  : in  std_logic_vector(C_S00_AXI_ADDR_WIDTH - 1 downto 0);
            s00_axi_arprot  : in  std_logic_vector(2 downto 0);
            s00_axi_arvalid : in  std_logic;
            s00_axi_arready : out std_logic;
            s00_axi_rdata   : out std_logic_vector(C_S00_AXI_DATA_WIDTH - 1 downto 0);
            s00_axi_rresp   : out std_logic_vector(1 downto 0);
            s00_axi_rvalid  : out std_logic;
            s00_axi_rready  : in  std_logic
        );
    end component AD4030;

    procedure SineGen(
        signal spi_clk_in : in  std_logic;
        signal sine_out   : out std_logic;
        signal sine_hex_out : out std_logic_vector(31 downto 0);
        signal cs_n : in std_logic) 
        is
        constant SIZE       : integer := 24;
        file     input_file : text;
        variable file_line  : line;
        variable hex_val    : std_logic_vector(23 downto 0);
        variable sine_hex    : std_logic_vector(31 downto 0);
    begin
    
        -- Open the file generated by your Python script
        file_open(input_file, "sine_data.txt", read_mode);

        while not endfile(input_file) loop
            readline(input_file, file_line);
            hread(file_line, hex_val);  -- Use 'hread' for Hex, 'read' for Integer
            sine_hex := x"00" & hex_val;
            wait until (cs_n ='0');
            sine_hex_out <= sine_hex;
            for i in SIZE - 1 downto 0 loop
                wait until rising_edge(spi_clk_in);
                sine_out <= sine_hex(i);
            end loop;
        end loop;

        file_close(input_file);

    end procedure SineGen;

begin

    AD4030_inst : AD4030
        generic map(
            C_S00_AXI_DATA_WIDTH   => 32,
            C_S00_AXI_ADDR_WIDTH   => 32,
            C_M00_AXIS_TDATA_WIDTH => 32,
            C_M00_AXIS_START_COUNT => 32
        )
        port map(
            clk_in          => clk,
            rst_n_in        => rst_n,
            cs_n_out        => cs_n,
            busy_in         => busy,
            miso0_in        => miso0,
            miso1_in        => miso1,
            miso2_in        => miso2,
            miso3_in        => miso3,
            sclk_out        => sclk,
            mosi_out        => mosi,
            conv_out        => conv,
            s00_axi_aclk    => clk,
            s00_axi_aresetn => rst_n,
            s00_axi_awaddr  => s00_axi_awaddr,
            s00_axi_awprot  => s00_axi_awprot,
            s00_axi_awvalid => s00_axi_awvalid,
            s00_axi_awready => s00_axi_awready,
            s00_axi_wdata   => s00_axi_wdata,
            s00_axi_wstrb   => s00_axi_wstrb,
            s00_axi_wvalid  => s00_axi_wvalid,
            s00_axi_wready  => s00_axi_wready,
            s00_axi_bresp   => s00_axi_bresp,
            s00_axi_bvalid  => s00_axi_bvalid,
            s00_axi_bready  => s00_axi_bready,
            s00_axi_araddr  => s00_axi_araddr,
            s00_axi_arprot  => s00_axi_arprot,
            s00_axi_arvalid => s00_axi_arvalid,
            s00_axi_arready => s00_axi_arready,
            s00_axi_rdata   => s00_axi_rdata,
            s00_axi_rresp   => s00_axi_rresp,
            s00_axi_rvalid  => s00_axi_rvalid,
            s00_axi_rready  => s00_axi_rready
        );

    clock_generator_proc : process is
    begin
        wait for clock_period / 2;
        clk <= '0';
        wait for clock_period / 2;
        clk <= '1';

    end process clock_generator_proc;

    adc_busy_proc : process
    begin
        wait until rising_edge(conv); 
        busy <= '1';
        wait for 300 ns;
        busy <= '0';
    end process adc_busy_proc;

    uut : process is

    begin
        -- Init 
        rst_n           <= '0';
        miso0           <= '0';
        miso1           <= '0';
        miso2           <= '0';
        miso3           <= '0';
        s00_axi_araddr  <= (others => '0');
        s00_axi_awaddr  <= (others => '0');
        s00_axi_wdata   <= (others => '0');
        s00_axi_wstrb   <= (others => '0');
        s00_axi_bready  <= '0';
        s00_axi_rready  <= '0';
        s00_axi_awprot  <= (others => '0');
        s00_axi_awvalid <= '0';
        s00_axi_wvalid  <= '0';
        s00_axi_arprot  <= (others => '0');
        s00_axi_arvalid <= '0';
        wait for 100 ns;
        rst_n           <= '1';

        SineGen(spi_clk_in => sclk,
                sine_out => miso0,
                sine_hex_out =>sine_hex,
                cs_n => cs_n);
        wait;

    end process uut;

end architecture testbench;

