library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.ad4030_pkg.all;
use ieee.std_logic_textio.all;
use std.textio.all;
library xil_defaultlib;

entity ad4030_axi_tb is
end entity ad4030_axi_tb;

architecture testbench of ad4030_axi_tb is

    constant clock_period : time    := 10 ns; -- 100 MHz
    constant DATA_SIZE    : integer := 32;
    constant ADDR_SIZE    : integer := 8;

    signal clk   : std_logic;
    signal rst_n : std_logic;

    -- AD4030 
    signal cs_n               : std_logic;
    signal busy               : std_logic;
    signal miso0              : std_logic;
    signal miso1              : std_logic;
    signal miso2              : std_logic;
    signal miso3              : std_logic;
    signal sclk               : std_logic;
    signal mosi               : std_logic;
    signal conv               : std_logic;
    -- AXI4 Lite interface
    signal s_axi_awaddr       : std_logic_vector(ADDR_SIZE - 1 downto 0);
    signal s_axi_awprot       : std_logic_vector(2 downto 0);
    signal s_axi_awvalid      : std_logic;
    signal s_axi_awready      : std_logic;
    signal s_axi_wdata        : std_logic_vector(DATA_SIZE - 1 downto 0);
    signal s_axi_wstrb        : std_logic_vector(3 downto 0);
    signal s_axi_wvalid       : std_logic;
    signal s_axi_wready       : std_logic;
    signal s_axi_bresp        : std_logic_vector(1 downto 0);
    signal s_axi_bvalid       : std_logic;
    signal s_axi_bready       : std_logic;
    signal s_axi_araddr       : std_logic_vector(ADDR_SIZE - 1 downto 0);
    signal s_axi_arprot       : std_logic_vector(2 downto 0);
    signal s_axi_arvalid      : std_logic;
    signal s_axi_arready      : std_logic;
    signal s_axi_rdata        : std_logic_vector(DATA_SIZE - 1 downto 0);
    signal s_axi_rresp        : std_logic_vector(1 downto 0);
    signal s_axi_rvalid       : std_logic;
    signal s_axi_rready       : std_logic;
    -- Testbench support data
    signal sine_hex           : std_logic_vector(DATA_SIZE - 1 downto 0);
    signal m_axi_rdata        : std_logic_vector(DATA_SIZE - 1 downto 0);
    --signal m_axi_awaddr           : std_logic_vector(ADDR_SIZE - 1 downto 0);
    --signal m_axi_wdata            : std_logic_vector(DATA_SIZE - 1 downto 0);
    signal mode               : std_logic_vector(1 downto 0);
    signal run_sine_generator : std_logic;

    component AD4030
        generic(
            DATA_SIZE         : integer;
            ADRR_SIZE         : integer;
            SPI_CLK_DIV       : natural;
            PULSE_WIDTH_SIZE  : natural;
            PULSE_PERIOD_SIZE : natural
        );
        port(
            clk_in          : in  std_logic;
            rst_n_in        : in  std_logic;
            cs_n_out        : out std_logic;
            busy_in         : in  std_logic;
            miso0_in        : in  std_logic;
            miso1_in        : in  std_logic;
            miso2_in        : in  std_logic;
            miso3_in        : in  std_logic;
            sclk_out        : out std_logic;
            mosi_out        : out std_logic;
            conv_out        : out std_logic;
            s00_axi_aclk    : in  std_logic;
            s00_axi_aresetn : in  std_logic;
            s00_axi_awaddr  : in  std_logic_vector(ADRR_SIZE - 1 downto 0);
            s00_axi_awprot  : in  std_logic_vector(2 downto 0);
            s00_axi_awvalid : in  std_logic;
            s00_axi_awready : out std_logic;
            s00_axi_wdata   : in  std_logic_vector(DATA_SIZE - 1 downto 0);
            s00_axi_wstrb   : in  std_logic_vector((DATA_SIZE / 8) - 1 downto 0);
            s00_axi_wvalid  : in  std_logic;
            s00_axi_wready  : out std_logic;
            s00_axi_bresp   : out std_logic_vector(1 downto 0);
            s00_axi_bvalid  : out std_logic;
            s00_axi_bready  : in  std_logic;
            s00_axi_araddr  : in  std_logic_vector(ADRR_SIZE - 1 downto 0);
            s00_axi_arprot  : in  std_logic_vector(2 downto 0);
            s00_axi_arvalid : in  std_logic;
            s00_axi_arready : out std_logic;
            s00_axi_rdata   : out std_logic_vector(DATA_SIZE - 1 downto 0);
            s00_axi_rresp   : out std_logic_vector(1 downto 0);
            s00_axi_rvalid  : out std_logic;
            s00_axi_rready  : in  std_logic
        );
    end component AD4030;

    procedure sine_gen(
        signal spi_clk_in   : in  std_logic;
        signal sine_out     : out std_logic;
        signal sine_hex_out : out std_logic_vector(31 downto 0);
        signal cs_n         : in  std_logic) is

        constant SIZE       : integer := 24;
        file     input_file : text;
        variable file_line  : line;
        variable hex_val    : std_logic_vector(23 downto 0);
        variable sine_hex   : std_logic_vector(DATA_SIZE - 1 downto 0);

    begin

        -- Open the file generated by your Python script
        file_open(input_file, "sine_data.txt", read_mode);

        while not endfile(input_file) loop
            readline(input_file, file_line);
            hread(file_line, hex_val);  -- Use 'hread' for Hex, 'read' for Integer
            sine_hex     := x"00" & hex_val;
            wait until (cs_n = '0');
            sine_hex_out <= sine_hex;
            for i in SIZE - 1 downto 0 loop
                wait until rising_edge(spi_clk_in);
                sine_out <= sine_hex(i);
            end loop;
        end loop;

        file_close(input_file);

    end procedure sine_gen;

    procedure sine_gen_v2(
        signal spi_clk_in   : in  std_logic;
        signal miso0_out    : out std_logic;
        signal miso1_out    : out std_logic;
        signal miso2_out    : out std_logic;
        signal miso3_out    : out std_logic;
        signal sine_hex_out : out std_logic_vector(31 downto 0);
        signal cs_n_in      : in  std_logic;
        signal mode_in      : in  std_logic_vector(1 downto 0);
        signal run          : in  std_logic) is

        constant SIZE       : integer := 24;
        file     input_file : text;
        variable file_line  : line;
        variable hex_val    : std_logic_vector(23 downto 0);
        variable sine_hex   : std_logic_vector(DATA_SIZE - 1 downto 0);

    begin

        -- Open the file generated by your Python script
        file_open(input_file, "sine_data.txt", read_mode);

        while not endfile(input_file) loop
            readline(input_file, file_line);
            hread(file_line, hex_val);  -- Use 'hread' for Hex, 'read' for Integer
            sine_hex     := x"00" & hex_val;
            wait until (cs_n = '0');
            sine_hex_out <= sine_hex;
            case mode_in is
                when ONE_LINE =>
                    one_miso_line(input => sine_hex,
                                  size  => SIZE,
                                  cs    => cs_n_in,
                                  sclk  => spi_clk_in,
                                  miso0 => miso0_out,
                                  miso1 => miso1_out,
                                  miso2 => miso2_out,
                                  miso3 => miso3_out);
                when TWO_LINES =>
                    two_miso_lines(input => sine_hex,
                                   size  => SIZE / 2,
                                   cs    => cs_n_in,
                                   sclk  => spi_clk_in,
                                   miso0 => miso0_out,
                                   miso1 => miso1_out,
                                   miso2 => miso2_out,
                                   miso3 => miso3_out);
                when FOUR_LINES =>
                    four_miso_lines(input => sine_hex,
                                    size  => SIZE / 4,
                                    cs    => cs_n_in,
                                    sclk  => spi_clk_in,
                                    miso0 => miso0_out,
                                    miso1 => miso1_out,
                                    miso2 => miso2_out,
                                    miso3 => miso3_out);
                when others => null;
                    one_miso_line(input => sine_hex,
                                  size  => SIZE,
                                  cs    => cs_n_in,
                                  sclk  => spi_clk_in,
                                  miso0 => miso0_out,
                                  miso1 => miso1_out,
                                  miso2 => miso2_out,
                                  miso3 => miso3_out);
            end case;

            if (run /= '1') then
                exit;
            end if;

        end loop;

        file_close(input_file);

    end procedure sine_gen_v2;

    procedure axi_read_control(signal clk_in    : in  std_logic;
                               signal arvalid   : out std_logic;
                               signal arready   : in  std_logic;
                               signal rvalid    : in  std_logic;
                               signal rready    : out std_logic;
                               signal rdata_out : out std_logic_vector(DATA_SIZE - 1 downto 0);
                               signal rdata_in  : in  std_logic_vector(DATA_SIZE - 1 downto 0)) is

    begin
        arvalid <= '1';
        loop
            wait until rising_edge(clk_in);
            exit when (arready = '1');
        end loop;
        arvalid <= '0';

        rready <= '1';
        loop
            wait until rising_edge(clk_in);
            if (rvalid = '1') then
                rdata_out <= rdata_in;
                exit;
            end if;
        end loop;
        rready <= '0';

    end procedure axi_read_control;

    procedure axi_write_control(
        signal clk_in  : in  std_logic;
        signal awvalid : out std_logic;
        signal awready : in  std_logic;
        signal wvalid  : out std_logic;
        signal wready  : in  std_logic;
        signal bvalid  : in  std_logic;
        signal bready  : out std_logic
    ) is
        variable aw_done : boolean := false;
        variable w_done  : boolean := false;
    begin
        -- Start both phases
        awvalid <= '1';
        wvalid  <= '1';
        bready  <= '1';                 -- Ready for the response whenever it comes
        wait for 0 ns;

        loop
            wait until rising_edge(clk_in);

            -- Check Address Handshake
            if awready = '1' then
                awvalid <= '0';
                aw_done := true;
            end if;

            -- Check Data Handshake
            if wready = '1' then
                wvalid <= '0';
                w_done := true;
            end if;

            exit when (aw_done and w_done);
        end loop;

        -- Wait for Response (B Channel)
        loop
            if bvalid = '1' then
                exit;
            end if;
            wait until rising_edge(clk_in);
        end loop;

        bready <= '0';
    end procedure;

begin

    AD4030_inst : AD4030
        generic map(
            DATA_SIZE         => 32,
            ADRR_SIZE         => 8,
            SPI_CLK_DIV       => 10,
            PULSE_WIDTH_SIZE  => 40,
            PULSE_PERIOD_SIZE => 800
        )
        port map(
            clk_in          => clk,
            rst_n_in        => rst_n,
            cs_n_out        => cs_n,
            busy_in         => busy,
            miso0_in        => miso0,
            miso1_in        => miso1,
            miso2_in        => miso2,
            miso3_in        => miso3,
            sclk_out        => sclk,
            mosi_out        => mosi,
            conv_out        => conv,
            s00_axi_aclk    => clk,
            s00_axi_aresetn => rst_n,
            s00_axi_awaddr  => s_axi_awaddr,
            s00_axi_awprot  => s_axi_awprot,
            s00_axi_awvalid => s_axi_awvalid,
            s00_axi_awready => s_axi_awready,
            s00_axi_wdata   => s_axi_wdata,
            s00_axi_wstrb   => s_axi_wstrb,
            s00_axi_wvalid  => s_axi_wvalid,
            s00_axi_wready  => s_axi_wready,
            s00_axi_bresp   => s_axi_bresp,
            s00_axi_bvalid  => s_axi_bvalid,
            s00_axi_bready  => s_axi_bready,
            s00_axi_araddr  => s_axi_araddr,
            s00_axi_arprot  => s_axi_arprot,
            s00_axi_arvalid => s_axi_arvalid,
            s00_axi_arready => s_axi_arready,
            s00_axi_rdata   => s_axi_rdata,
            s00_axi_rresp   => s_axi_rresp,
            s00_axi_rvalid  => s_axi_rvalid,
            s00_axi_rready  => s_axi_rready
        );

    clock_generator_proc : process is
    begin
        wait for clock_period / 2;
        clk <= '0';
        wait for clock_period / 2;
        clk <= '1';

    end process clock_generator_proc;

    adc_busy_proc : process
    begin
        wait until rising_edge(conv);
        busy <= '1';
        wait for 300 ns;
        busy <= '0';
    end process adc_busy_proc;

    sine_wave_proc : process is
    begin
        wait until (rst_n = '1');

        -- sine_gen(spi_clk_in   => sclk,
        --          sine_out     => miso0,
        --          sine_hex_out => sine_hex,
        --          cs_n         => cs_n);
        sine_gen_v2(spi_clk_in   => sclk,
                    miso0_out    => miso0,
                    miso1_out    => miso1,
                    miso2_out    => miso2,
                    miso3_out    => miso3,
                    sine_hex_out => sine_hex,
                    cs_n_in      => cs_n,
                    mode_in      => mode,
                    run          => run_sine_generator);

    end process sine_wave_proc;

    uut : process is
    begin
        -- Init 

        rst_n <= '0';

        s_axi_araddr       <= (others => '0');
        s_axi_awaddr       <= (others => '0');
        s_axi_wdata        <= (others => '0');
        s_axi_wstrb        <= (others => '0');
        s_axi_bready       <= '0';
        s_axi_rready       <= '0';
        s_axi_awprot       <= (others => '0');
        s_axi_awvalid      <= '0';
        s_axi_wvalid       <= '0';
        s_axi_arprot       <= (others => '0');
        s_axi_arvalid      <= '0';
        m_axi_rdata        <= (others => '0');
        mode               <= ONE_LINE;
        run_sine_generator <= '1';
        wait for 100 ns;
        rst_n              <= '1';
        wait for 2.5 us;

        -- Readout test 

        loop
            s_axi_araddr <= SPI_STATUS_INDEX;
            axi_read_control(clk_in    => clk,
                             arvalid   => s_axi_arvalid,
                             arready   => s_axi_arready,
                             rvalid    => s_axi_rvalid,
                             rready    => s_axi_rready,
                             rdata_out => m_axi_rdata,
                             rdata_in  => s_axi_rdata);
            wait for clock_period;
            if (m_axi_rdata = x"00_00_00_03") then
                exit;
            end if;
        end loop;

        s_axi_araddr <= ADC_READOUT_INDEX;
        wait for 10 ns;
        axi_read_control(clk_in    => clk,
                         arvalid   => s_axi_arvalid,
                         arready   => s_axi_arready,
                         rvalid    => s_axi_rvalid,
                         rready    => s_axi_rready,
                         rdata_out => m_axi_rdata,
                         rdata_in  => s_axi_rdata);

        -- Write test : CNV_PERIOD_INDEX 

        s_axi_awaddr <= CNV_PERIOD_INDEX;
        s_axi_wdata  <= x"00_00_01_90";
        s_axi_wstrb  <= "1111";
        wait for 10 ns;
        axi_write_control(clk_in  => clk,
                          awvalid => s_axi_awvalid,
                          awready => s_axi_awready,
                          wready  => s_axi_wready,
                          wvalid  => s_axi_wvalid,
                          bvalid  => s_axi_bvalid,
                          bready  => s_axi_bready);

        s_axi_araddr <= CNV_PERIOD_INDEX;
        wait for 10 ns;
        axi_read_control(clk_in    => clk,
                         arvalid   => s_axi_arvalid,
                         arready   => s_axi_arready,
                         rvalid    => s_axi_rvalid,
                         rready    => s_axi_rready,
                         rdata_out => m_axi_rdata,
                         rdata_in  => s_axi_rdata);

        s_axi_awaddr <= CNV_PERIOD_INDEX;
        wait for 5 us;
        s_axi_wdata  <= x"00_00_00_C8";
        s_axi_wstrb  <= "1111";
        wait for 10 ns;
        axi_write_control(clk_in  => clk,
                          awvalid => s_axi_awvalid,
                          awready => s_axi_awready,
                          wready  => s_axi_wready,
                          wvalid  => s_axi_wvalid,
                          bvalid  => s_axi_bvalid,
                          bready  => s_axi_bready);

        s_axi_araddr <= CNV_PERIOD_INDEX;
        wait for 10 ns;
        axi_read_control(clk_in    => clk,
                         arvalid   => s_axi_arvalid,
                         arready   => s_axi_arready,
                         rvalid    => s_axi_rvalid,
                         rready    => s_axi_rready,
                         rdata_out => m_axi_rdata,
                         rdata_in  => s_axi_rdata);

        -- Write test : ADC_CFG_INDEX : Change MISO channel count 

        -- Enable ADC configuration mode        
        s_axi_awaddr <= ADC_CFG_INDEX;
        s_axi_wdata  <= ADC_ENABLE_CFG_CMD;
        s_axi_wstrb  <= "1111";
        wait for 10 ns;
        axi_write_control(clk_in  => clk,
                          awvalid => s_axi_awvalid,
                          awready => s_axi_awready,
                          wready  => s_axi_wready,
                          wvalid  => s_axi_wvalid,
                          bvalid  => s_axi_bvalid,
                          bready  => s_axi_bready);
                          
        loop
            s_axi_araddr <= SPI_STATUS_INDEX;
            axi_read_control(clk_in    => clk,
                             arvalid   => s_axi_arvalid,
                             arready   => s_axi_arready,
                             rvalid    => s_axi_rvalid,
                             rready    => s_axi_rready,
                             rdata_out => m_axi_rdata,
                             rdata_in  => s_axi_rdata);
            wait for clock_period;
            if (m_axi_rdata = x"00_00_00_01") then
                exit;
            end if;
        end loop;
        
        -- Change LANE_MD 

        s_axi_awaddr <= ADC_CFG_INDEX;
        s_axi_wdata  <= x"00" & ADC_MODES_ADDR & FOUR_LINES & "000000"; -- 31 downto 24 : always 0; 23 downto 8 : adc config address; 7 downto 0 : adc config data
        s_axi_wstrb  <= "1111";
        wait for 10 ns;
        axi_write_control(clk_in  => clk,
                          awvalid => s_axi_awvalid,
                          awready => s_axi_awready,
                          wready  => s_axi_wready,
                          wvalid  => s_axi_wvalid,
                          bvalid  => s_axi_bvalid,
                          bready  => s_axi_bready);
        
         loop
            s_axi_araddr <= SPI_STATUS_INDEX;
            axi_read_control(clk_in    => clk,
                             arvalid   => s_axi_arvalid,
                             arready   => s_axi_arready,
                             rvalid    => s_axi_rvalid,
                             rready    => s_axi_rready,
                             rdata_out => m_axi_rdata,
                             rdata_in  => s_axi_rdata);
            wait for clock_period;
            if (m_axi_rdata = x"00_00_00_01") then
                exit;
            end if;
        end loop;

        -- Disable ADC configuration mode
        s_axi_awaddr <= ADC_CFG_INDEX;
        s_axi_wdata  <= x"00" & ADC_EXIT_CFG_MD_ADDR & "00000001"; -- 31 downto 24 : always 0; 23 downto 8 : adc config address; 7 downto 0 : adc config data
        s_axi_wstrb  <= "1111";
        wait for 10 ns;
        axi_write_control(clk_in  => clk,
                          awvalid => s_axi_awvalid,
                          awready => s_axi_awready,
                          wready  => s_axi_wready,
                          wvalid  => s_axi_wvalid,
                          bvalid  => s_axi_bvalid,
                          bready  => s_axi_bready);

        --wait until (conv = '1');
        mode <= FOUR_LINES;
        
        loop
            s_axi_araddr <= SPI_STATUS_INDEX;
            axi_read_control(clk_in    => clk,
                             arvalid   => s_axi_arvalid,
                             arready   => s_axi_arready,
                             rvalid    => s_axi_rvalid,
                             rready    => s_axi_rready,
                             rdata_out => m_axi_rdata,
                             rdata_in  => s_axi_rdata);
            wait for clock_period;
            if (m_axi_rdata = x"00_00_00_01") then
                exit;
            end if;
        end loop;
        -- wait until s_axi_rvalid = '1';

        --    wait for 3 us;

        loop
            s_axi_araddr <= SPI_STATUS_INDEX;
            axi_read_control(clk_in    => clk,
                             arvalid   => s_axi_arvalid,
                             arready   => s_axi_arready,
                             rvalid    => s_axi_rvalid,
                             rready    => s_axi_rready,
                             rdata_out => m_axi_rdata,
                             rdata_in  => s_axi_rdata);
            wait for clock_period;
            if (m_axi_rdata = x"00_00_00_03") then
                exit;
            end if;
        end loop;

        s_axi_araddr <= ADC_READOUT_INDEX;
        wait for 10 ns;
        axi_read_control(clk_in    => clk,
                         arvalid   => s_axi_arvalid,
                         arready   => s_axi_arready,
                         rvalid    => s_axi_rvalid,
                         rready    => s_axi_rready,
                         rdata_out => m_axi_rdata,
                         rdata_in  => s_axi_rdata);

        loop
            s_axi_araddr <= SPI_STATUS_INDEX;
            axi_read_control(clk_in    => clk,
                             arvalid   => s_axi_arvalid,
                             arready   => s_axi_arready,
                             rvalid    => s_axi_rvalid,
                             rready    => s_axi_rready,
                             rdata_out => m_axi_rdata,
                             rdata_in  => s_axi_rdata);
            wait for clock_period;
            if (m_axi_rdata = x"00_00_00_03") then
                exit;
            end if;
        end loop;

        s_axi_araddr <= ADC_READOUT_INDEX;
        wait for 10 ns;
        axi_read_control(clk_in    => clk,
                         arvalid   => s_axi_arvalid,
                         arready   => s_axi_arready,
                         rvalid    => s_axi_rvalid,
                         rready    => s_axi_rready,
                         rdata_out => m_axi_rdata,
                         rdata_in  => s_axi_rdata);
        wait;

    end process uut;

end architecture testbench;

