domain_path: /home/grzegorz/git/ARTY_Z7/AD4030/Software/vitis/AD4030-Voltage/export/AD4030-Voltage/sw/freertos_ps7_cortexa9_0
app_src_dir: /opt/Xilinx/Vitis/2024.1/data/embeddedsw/lib/sw_apps/freertos_hello_world
template: freertos_hello_world
